language: node_js
node_js: "12"
branches:
  only:
    - test/ci
os:
  - linux
  - osx
  - windows
before_install:
  - openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in github_deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config user.name "Travis CI BOT"
  - git config user.email "travis@Travis-["$TRAVIS_OS_NAME"]-6.local"
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config; fi
  - git remote set-url origin git@github.com:beajer/oss-browser.git
script:
  - git pull origin test/ci --no-rebase
  - npm run build-crc64 && if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run test-crc64; fi
  - git add node/
  - git commit -m "chore:\s[skip travis] build native addon on ["$TRAVIS_OS_NAME"]"
  - git push origin HEAD:test/ci
