language: node_js
node_js: "12"
branches:
  only:
    - test/ci
env:
  global:
    - GH: https://github.com/beajer/oss-browser.git
    - secure: "c0Tnsi67xqYVS2ENRwg7BpDrgdLjLBvxrWB5P+EOElWjAtzbAHi9r70Fp0cg0Sjok0iTaVlSKzNw9IdABxvOsp3PXN4MMTqPb+NwgV/2i/O4QIpsRrlMAYlFIjNpY9l0Ju8O8nzR77CUOAZvJJLyWI2zEZWElq/yh6vGHDqlgoJ0nbhBS3aBPe8HlCCcJbFrodulpkqDFlh2hIZ58YzJ9mpy2DJnFlDLUIMCPNHskKt5Lb5u3I0PkcupZaDs6MMXe9esNKR9fTLbmwOfVojloZHmuWwviu29KJ7UdoZdxx5LtK47pDAR4/WngClLtKk4FHcbDMqoGdkf5kw6JqFr1LcQhxaFbq3ScVCXFeeSNR/e3H/acN9mTy+ZhQVpZQrx+kG9wyqLoLbgDHmBNyV3yOOnGy5oM5dsAN1nRaBQ4+n6ZiXf2fCIjsNbqcNxDR6w0f+yQD1UvFjPdXYsM0spPuMI9+6Lo4DivsjfLb4qOGCaGSTgLRF1Am+l+nFv84jXQ357TpQ8TNyDEWTdu7Iz6DOdRVYcp4jECusLgO4ekSnHO6F9unxZfCLYLASrmnENqpkgWlbFwBejNEU3kA7YIZuVd15SQbU3htE7CdhTtR/AVbYR1F6UwbuGfi0wpgyHnHpGbJTCLExfCPRVuaXOa1ryVR0eoLFvh6QD/V/W670="
os:
  - linux
  - osx
  - windows
before_install:
  - npm cache clean --force
  - rm -rf node_modules package-lock.json
script:
  - npm run build-crc64 && if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run test-crc64; fi
after_success:
  - openssl aes-256-cbc -k "$travis_key_password" -nopad -d -md sha256 -a -in ./tools/travis_key.enc -out travis_key
  - echo "Host github.com" > ~/.ssh/config
  - echo "  IdentityFile  $(pwd)/travis_key" >> ~/.ssh/config
  - chmod 400 travis_key
  - git config user.name "Travis CI"
  - git config user.email "919060679@qq.com"
  - git add node/
  - git commit -m "[skip travis] ci:build crc64 for $TRACIS_OS_NAME on travis"
  - git push ${GH} test/ci:test/ci
