language: "node_js"

node_js: '12'

branches:
  only:
  - test/ci

os:
  - linux
  - osx
  - windows

before_install:
  - npm cache clean --force
  - rm -rf node_modules package-lock.json

script: 
  - npm run build-crc64
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run test-crc64; fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: node/**/*
  skip_cleanup: true
  on:
    tags: true