language: "node_js"

node_js: '12'

branches:
  only:
  - test/ci

os:
  - linux
  - osx
  - windows

before_install:
  - npm cache clean --force
  - rm -rf node_modules package-lock.json

script: 
  - npm run build-crc64
  - npm run test-crc64
